<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>BloonsArchipelago</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Nullable>enable</Nullable>
        <AssemblyName>BloonsArchipelago</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Optimize>False</Optimize>
        <DebugType>embedded</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <Content Include=".github\workflows\build.yml" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Archipelago.MultiClient.Net" Version="6.6.0" />
      <PackageReference Include="ILRepack" Version="2.0.40">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <Import Project="btd6.targets" />
</Project>
